// categories.jsx
export const categoriesMap = {
    'Electronics': 'Electrónica',
    'Clothing': 'Ropa',
    'Home': 'Hogar',
    'Sports': 'Deportes',
    'Toys': 'Juguetes',
    'Furniture': 'Muebles',
    'Tools': 'Herramientas',
    'Beauty': 'Belleza',
    'Health': 'Salud',
    'Automobiles': 'Automóviles',
    'Books': 'Libros',
    'Music': 'Música',
    'Video Games': 'Videojuegos',
    'Kitchen': 'Cocina',
    'Gardening': 'Jardinería',
    'Pet Accessories': 'Accesorios para Mascotas',
    'Computers': 'Computadoras',
    'Telephony': 'Telefonía',
    'Photography': 'Fotografía',
    'Office': 'Oficina',
    'Women’s Fashion': 'Moda Femenina',
    'Men’s Fashion': 'Moda Masculina',
    'Footwear': 'Calzado',
    'Watches': 'Relojes',
    'Jewelry': 'Joyería',
    'Travel Items': 'Artículos de Viaje',
    'Baby Items': 'Artículos para Bebés',
    'Outdoor Sports': 'Deportes al Aire Libre',
    'Camping': 'Camping',
    'Fishing': 'Pesca',
    'Bicycles': 'Bicicletas',
    'Yoga and Meditation': 'Yoga y Meditación',
    'Crafts': 'Artesanías',
    'Decoration': 'Decoración',
    'Art': 'Arte',
    'Musical Instruments': 'Instrumentos Musicales',
    'Eco-friendly Products': 'Productos Ecológicos',
    'Office Supplies': 'Suministros de Oficina',
    'Smart Home Products': 'Productos para el Hogar Inteligente',
    'Car Accessories': 'Accesorios para Autos',
    'Beach Items': 'Artículos de Playa',
    'Sportswear': 'Ropa Deportiva',
    'Bedding': 'Ropa de Cama',
    'Kitchenware': 'Utensilios de Cocina',
    'Cleaning Products': 'Productos de Limpieza',
    'Hair Care Products': 'Productos para el Cuidado del Cabello',
    'Skin Care Products': 'Productos para el Cuidado de la Piel',
    'Personal Care Products': 'Productos para el Cuidado Personal',
    'Fitness Products': 'Productos para Fitness',
    'Pet Products': 'Productos para Mascotas'
};
